[package]
name = "reustmann"
version = "0.1.0"
authors = ["Kerosene2000 <renault.cle@gmail.com>"]
description = "Reustmann is a Von Neumann architecture"
documentation = "http://Kerosene2000.github.io/reustmann/reustmann/"
repository = "https://github.com/Kerosene2000/Reustmann"
license = "MIT"

[[bin]]
name = "reustmann"
doc = false

[dependencies]
colorify = "0.2"
